Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "ros-kinetic"
  config.vm.provision "shell", run: "always", path: "provisioning.sh"
  config.vm.provision "shell", run: "always", privileged: false, path: "user_provisioning.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ros-kinetic"
    vb.gui = "true"
    vb.memory = "2048"
  end
end
